#!/bin/sh
if [ -f /tmp/skin-user-hd.xml ]; then
    mv -f /tmp/skin-user-hd.xml /usr/lib/enigma2/python/Plugins/Extensions/KravenHD/data/HD/skin-user.xml
fi
if [ -f /tmp/skin-user-fhd.xml ]; then
    mv -f /tmp/skin-user-fhd.xml /usr/lib/enigma2/python/Plugins/Extensions/KravenHD/data/FHD/skin-user.xml
fi
echo " .##....##.########.....###....##.....##.########.##....## "
echo " .##...##..##.....##...##.##...##.....##.##.......###...## "
echo " .##..##...##.....##..##...##..##.....##.##.......####..## "
echo " .#####....########..##.....##.##.....##.######...##.##.## "
echo " .##..##...##...##...#########..##...##..##.......##..#### "
echo " .##...##..##....##..##.....##...##.##...##.......##...### "
echo " .##....##.##.....##.##.....##....###....########.##....## "
echo " .........................................................."
echo "                    .##....##..#######...                  "
echo "                    .##....##..##....##..                  "
echo "                    .##....##..##.....##.                  "
echo "                    .########..##.....##.                  "
echo "                    .##....##..##.....##.                  "
echo "                    .##....##..##....##..                  "
echo "                    .##....##..#######...                  "
echo "                                                           "
echo "               ...Skin successful installed.               "
